/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by '16001854' at '6/26/20 3:18 PM' with Gradle 2.14
 *
 * @author 16001854, @date 6/26/20 3:18 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
